"""First revision

Revision ID: 1
Revises: 
Create Date: 2025-10-17 14:10:06.058072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String

# revision identifiers, used by Alembic.
revision: str = '1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_authentication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', String(), nullable=False),
    sa.Column('fullname', String(), nullable=False),
    sa.Column('password', String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_authentication_email'), 'platform_authentication', ['email'], unique=True)
    op.create_index(op.f('ix_platform_authentication_id'), 'platform_authentication', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_authentication_id'), table_name='platform_authentication')
    op.drop_index(op.f('ix_platform_authentication_email'), table_name='platform_authentication')
    op.drop_table('platform_authentication')
    # ### end Alembic commands ###
